[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'python manage.py migrate --noinput && gunicorn --bind 0.0.0.0:$PORT cyprus_api.wsgi:application'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
